language: perl
matrix:
 include:
  - perl: "5.20"
    env: USE_MAP_TUBE_VERSION=latest
  - perl: "5.20"
    # the version before other_link feature
    env: USE_MAP_TUBE_VERSION=2.88
  - perl: "5.18"
    env: USE_MAP_TUBE_VERSION=latest
  - perl: "5.18"
    # test with minimum version
    env: USE_MAP_TUBE_VERSION=2.38
  - perl: "5.16"
    env: USE_MAP_TUBE_VERSION=latest
  - perl: "5.14"
    env: USE_MAP_TUBE_VERSION=latest
  - perl: "5.12"
    env: USE_MAP_TUBE_VERSION=latest
  - perl: "5.10"
    env: USE_MAP_TUBE_VERSION=latest
  - perl: "5.8"
    # https://rt.cpan.org/Ticket/Display.html?id=107785
    env: USE_MAP_TUBE_VERSION=3.00
before_install:
 - '[ "$USE_MAP_TUBE_VERSION" != "latest" ] && cpanm --quiet --notest Map::Tube~"==$USE_MAP_TUBE_VERSION" || true'
sudo: false
